from analysis.utils import filter_sib_metrics_dict
from analysis.config import (
    SIB_LANG_CODE_MAP,
    METRICS_MT5SMALL_SIB_LORA_r64, METRICS_MT5SMALL_SIB_QLORA_r64, METRICS_MT5SMALL_SIB_FULLFINETUNE,
    METRICS_MT5BASE_SIB_LORA_r64, METRICS_MT5BASE_SIB_QLORA_r64, METRICS_MT5BASE_SIB_FULLFINETUNE,
    METRICS_MT5LARGE_SIB_LORA_r64, METRICS_MT5LARGE_SIB_QLORA_r64, METRICS_MT5LARGE_SIB_FULLFINETUNE,
    METRICS_BLOOM560M_SIB_LORA_r64, METRICS_BLOOM560M_SIB_QLORA_r64, METRICS_BLOOM560M_SIB_FULLFINETUNE,
    METRICS_BLOOM1B1_SIB_LORA_r64, METRICS_BLOOM1B1_SIB_QLORA_r64, METRICS_BLOOM1B1_SIB_FULLFINETUNE,
    METRICS_BLOOM1B7_SIB_LORA_r64, METRICS_BLOOM1B7_SIB_QLORA_r64, METRICS_BLOOM1B7_SIB_FULLFINETUNE,
)

metrics_dict_more_langs = {
    'METRICS_MT5SMALL_SIB_LORA_r64_MORE_LANGS': METRICS_MT5SMALL_SIB_LORA_r64,
    'METRICS_MT5BASE_SIB_LORA_r64_MORE_LANGS': METRICS_MT5BASE_SIB_LORA_r64,
    'METRICS_MT5LARGE_SIB_LORA_r64_MORE_LANGS': METRICS_MT5LARGE_SIB_LORA_r64,
    'METRICS_MT5SMALL_SIB_QLORA_r64_MORE_LANGS': METRICS_MT5SMALL_SIB_QLORA_r64,
    'METRICS_MT5BASE_SIB_QLORA_r64_MORE_LANGS': METRICS_MT5BASE_SIB_QLORA_r64,
    'METRICS_MT5LARGE_SIB_QLORA_r64_MORE_LANGS': METRICS_MT5LARGE_SIB_QLORA_r64,
    'METRICS_MT5SMALL_SIB_FULLFINETUNE_MORE_LANGS': METRICS_MT5SMALL_SIB_FULLFINETUNE,
    'METRICS_MT5BASE_SIB_FULLFINETUNE_MORE_LANGS': METRICS_MT5BASE_SIB_FULLFINETUNE,
    'METRICS_MT5LARGE_SIB_FULLFINETUNE_MORE_LANGS': METRICS_MT5LARGE_SIB_FULLFINETUNE,
    'METRICS_BLOOM560M_SIB_LORA_r64_MORE_LANGS': METRICS_BLOOM560M_SIB_LORA_r64,
    'METRICS_BLOOM1B1_SIB_LORA_r64_MORE_LANGS': METRICS_BLOOM1B1_SIB_LORA_r64,
    'METRICS_BLOOM1B7_SIB_LORA_r64_MORE_LANGS': METRICS_BLOOM1B7_SIB_LORA_r64,
    'METRICS_BLOOM560M_SIB_QLORA_r64_MORE_LANGS': METRICS_BLOOM560M_SIB_QLORA_r64,
    'METRICS_BLOOM1B1_SIB_QLORA_r64_MORE_LANGS': METRICS_BLOOM1B1_SIB_QLORA_r64,
    'METRICS_BLOOM1B7_SIB_QLORA_r64_MORE_LANGS': METRICS_BLOOM1B7_SIB_QLORA_r64,
    'METRICS_BLOOM560M_SIB_FULLFINETUNE_MORE_LANGS': METRICS_BLOOM560M_SIB_FULLFINETUNE,
    'METRICS_BLOOM1B1_SIB_FULLFINETUNE_MORE_LANGS': METRICS_BLOOM1B1_SIB_FULLFINETUNE,
    'METRICS_BLOOM1B7_SIB_FULLFINETUNE_MORE_LANGS': METRICS_BLOOM1B7_SIB_FULLFINETUNE,
}
# Keep only PAWS-X and XNLI languages for SIB (17 languages)
for key in metrics_dict_more_langs:
    metrics_dict_more_langs[key] = filter_sib_metrics_dict(metrics_dict_more_langs[key], SIB_LANG_CODE_MAP)

metrics_dict = {
    'METRICS_MT5SMALL_SIB_LORA_r64': METRICS_MT5SMALL_SIB_LORA_r64,
    'METRICS_MT5BASE_SIB_LORA_r64': METRICS_MT5BASE_SIB_LORA_r64,
    'METRICS_MT5LARGE_SIB_LORA_r64': METRICS_MT5LARGE_SIB_LORA_r64,
    'METRICS_MT5SMALL_SIB_QLORA_r64': METRICS_MT5SMALL_SIB_QLORA_r64,
    'METRICS_MT5BASE_SIB_QLORA_r64': METRICS_MT5BASE_SIB_QLORA_r64,
    'METRICS_MT5LARGE_SIB_QLORA_r64': METRICS_MT5LARGE_SIB_QLORA_r64,
    'METRICS_MT5SMALL_SIB_FULLFINETUNE': METRICS_MT5SMALL_SIB_FULLFINETUNE,
    'METRICS_MT5BASE_SIB_FULLFINETUNE': METRICS_MT5BASE_SIB_FULLFINETUNE,
    'METRICS_MT5LARGE_SIB_FULLFINETUNE': METRICS_MT5LARGE_SIB_FULLFINETUNE,
    'METRICS_BLOOM560M_SIB_LORA_r64': METRICS_BLOOM560M_SIB_LORA_r64,
    'METRICS_BLOOM1B1_SIB_LORA_r64': METRICS_BLOOM1B1_SIB_LORA_r64,
    'METRICS_BLOOM1B7_SIB_LORA_r64': METRICS_BLOOM1B7_SIB_LORA_r64,
    'METRICS_BLOOM560M_SIB_QLORA_r64': METRICS_BLOOM560M_SIB_QLORA_r64,
    'METRICS_BLOOM1B1_SIB_QLORA_r64': METRICS_BLOOM1B1_SIB_QLORA_r64,
    'METRICS_BLOOM1B7_SIB_QLORA_r64': METRICS_BLOOM1B7_SIB_QLORA_r64,
    'METRICS_BLOOM560M_SIB_FULLFINETUNE': METRICS_BLOOM560M_SIB_FULLFINETUNE,
    'METRICS_BLOOM1B1_SIB_FULLFINETUNE': METRICS_BLOOM1B1_SIB_FULLFINETUNE,
    'METRICS_BLOOM1B7_SIB_FULLFINETUNE': METRICS_BLOOM1B7_SIB_FULLFINETUNE,
}

# Keep only XNLI languages for SIB (15 languages)
for key in metrics_dict:
    metrics_dict[key] = filter_sib_metrics_dict(metrics_dict[key], SIB_LANG_CODE_MAP, dataset_langs_to_keep='xnli')


# Updating original variables
locals().update(metrics_dict)
locals().update(metrics_dict_more_langs)
print()
